controllers/CabinetController.php
<?php

namespace app\controllers;

use app\models\Commission;
use app\models\Transfer;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\HttpException;
use yii\bootstrap\ActiveForm;

use app\models\User;
use app\models\UserBalance;
use app\models\TransferForm;
use yii\helpers\Html;
use app\models\RlTransferCommission;
use app\models\RlUserCommission;

class CabinetController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['*'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function actionIndex()
    {
        $user = User::findOne(Yii::$app->user->identity->getId());
        if ($user) {
            $balance_value = '0.00 y.e.';
            $balance_date = '';
            if ($balance = $user->getBalance()) {
                /* @var \app\Models\UserBalance $balance */
                $balance_value = $balance->value . ' y.e.';
                $balance_date = $balance->getDateCreate();
                if ($date_update = $balance->getDateUpdate()) {
                    $balance_date = $date_update;
                }
            }
			$commission = false;
			$user_commis_desc = '';
			if ($rl_user_commission = RlUserCommission::findOne(['user_id' => $user->id])) {
				$commission = $rl_user_commission->getCommission();
				$user_commis_desc = $commission->description;
			}
			
            $transferFormModel = new TransferForm();

            if ($transferFormModel->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {

                $result = [];
                //Yii::$app->response->format = Response::FORMAT_JSON; 
                $transferFormModel->validate();
                if($transferFormModel->hasErrors()) {
                    foreach ($transferFormModel->getErrors() as $attribute => $errors) {
                        $result[Html::getInputId($transferFormModel, $attribute)] = $errors;
                    }
                    return $this->asJson(['validation' => $result]);
                }

                $errors = 0;
                if ($recipient_user = User::findOne(['email' => $transferFormModel->email])) {
                    $transfer = new Transfer;
                    $transfer->sender_user_id = $user->id;
                    $transfer->value = $transferFormModel->value;
                    $transfer->recipient_user_id = $recipient_user->id;
                    if ($transfer->save()) {
						if ($commission) {
							$rl_transfer_commis = new RlTransferCommission;
							$rl_transfer_commis->transfer_id = $transfer->id;
							$rl_transfer_commis->commission_id = $commission->id;
							if (!$rl_transfer_commis->save()) {
								$errors++;
							}
						} else {
							$errors++;
						}
                        if ($errors === 0) {
                            // С учётом комиссии
                            $valueWithCom = $transfer->getResultWithCommission();

                            $sender_user_balance = UserBalance::findOne(['user_id' => $user->id]);
                            $sender_user_balance->value = $sender_user_balance->value - $valueWithCom;
                            if (!$sender_user_balance->save()) {
                                Yii::$app->session->setFlash('error', 'Возникли ошибки при проведении операции.');
								return $this->refresh();

                            }
                            $recipient_user_balance = UserBalance::findOne(['user_id' => $recipient_user->id]);
                            $recipient_user_balance->value = $recipient_user_balance->value + $transferFormModel->value;
                            if (!$recipient_user_balance->save()) {
                                Yii::$app->session->setFlash('error', 'Возникли ошибки при проведении операции.');
								return $this->refresh();
                            }
							
							$transfer->total_value = $valueWithCom;
							$transfer->status = Transfer::STATUS_ACTIVE;
							if ($transfer->save()) {
								Yii::$app->session->setFlash('success', 'Операция успешно произведена.');
								return $this->asJson(['success' => true]);

							} else {
								Yii::$app->session->setFlash('error', 'Возникли ошибки при проведении операции.');
								return $this->refresh();
							}
							
                        } else {
                            Yii::$app->session->setFlash('error', 'Возникли ошибки при проведении операции.');
							return $this->refresh();
                        }
                    } else {
                        Yii::$app->session->setFlash('error', 'Возникли ошибки при проведении операции.');
						return $this->refresh();
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Возникли ошибки при проведении операции.');
					return $this->refresh();
                }
            }

            return $this->render('index', [
                'user' => $user,
                'user_balance_value' => $balance_value,
                'user_balance_date' => $balance_date,
                'transferFormModel' => $transferFormModel,
				'user_commis_desc' => $user_commis_desc
            ]);
        }
        throw new HttpException(404 ,'User not found');

    }

    public function actionCommissionResult($transfer_value)
    {
        $user = User::findOne(Yii::$app->user->identity->getId());
        if ($user) {
			
        }
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\RegisterForm;

use app\models\User;
use app\models\UserBalance;
use app\models\Commission;
use app\models\RlUserCommission;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays registration page.
     *
     * @return Response|string
     */
    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new RegisterForm(); 
        if ($model->load(Yii::$app->request->post())) {
			if ($model->validate()) {
				if ($user = $model->signup()) {
					
					$user_balance = new UserBalance;
					$user_balance->user_id = $user->id;
					$user_balance->value = 0;
					$user_balance->save();
					
					$dafault_commission = Commission::findOne(['base' => '1']);
					$rl_user_commission = new RlUserCommission;
					$rl_user_commission->user_id = $user->id;
					$rl_user_commission->commission_id = $dafault_commission->id;
					$rl_user_commission->save();
					
					if (Yii::$app->getUser()->login($user)) {
						return $this->goHome();
					}
				}
			}
        }
 
        return $this->render('register', [
            'model' => $model,
        ]);
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Добро пожаловать!</h1>
		<? if (Yii::$app->user->isGuest) { ?>
			<p class="lead">Вы можете стать нашим партнёром прямо сейчас.</p>
			<p><a class="btn btn-lg btn-success" href="<?=Url::to(['/register'])?>">Регистрация</a></p>
		<? } else { ?>
			<p><a class="btn btn-lg btn-success" href="<?=Url::to(['/cabinet/index'])?>">Личный кабинет</a></p>
		<? } ?>
    </div>

    <div class="body-content">

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для авторизации:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/register.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\RegisterForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>
		
        <div class="row">
            <div class="col-lg-5">
				
				<p>Пожалуйста, заполните следующие поля для регистрации:</p>

                <?php $form = ActiveForm::begin(['id' => 'register-form']); ?>
                    
					<?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'password')->passwordInput() ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
</div>